version: '3.8'

services:
  # Сервис для SessionApi
  sessionapi:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    networks:
      - webnet

  # Сервис для MatchMakingService
  matchmakingservice:
    build:
      context: .
      dockerfile: Dockerfile.mm
    ports:
      - "7878:7878"
    networks:
      - webnet

  # Сервис для NGINX
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
      # Монтируем конфигурацию NGINX
      - ./ssl:/etc/nginx/ssl  
      # Монтируем SSL сертификаты
    depends_on:
      - sessionapi
      - matchmakingservice
    networks:
      - webnet

networks:
  webnet:
    driver: bridge