apiVersion: apps/v1
kind: Deployment
metadata:
  name: matchmakingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matchmakingservice
  template:
    metadata:
      labels:
        app: matchmakingservice
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
      containers:
        - name: matchmakingservice
          image: "{{ .Values.matchmakingservice.image.repository }}:{{ .Values.matchmakingservice.image.tag }}"
          ports:
            - containerPort: {{ .Values.matchmakingservice.containerPort }}
          volumeMounts:
            - mountPath: /app/appsettings.json
              name: nginx-config
              subPath: appsettings.json