apiVersion: v1
kind: Service
metadata:
  name: matchmakingservice
spec:
  selector:
    app: matchmakingservice
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
  type: LoadBalancer