apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: "http"
      targetPort: 80
      nodePort: 30080
    - port: 443
      protocol: TCP
      name: "https"
      targetPort: 443
      nodePort: 30443
  selector:
    app: nginx