apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: nginx-config
          hostPath:
            path: ./nginx.conf
        - name: ssl-certs
          hostPath:
            path: ./ssl
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image }}"
          ports:
{{- range .Values.nginx.containerPorts }}
            - containerPort: {{ . }}
{{- end }}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
            - mountPath: /etc/nginx/ssl
              name: ssl-certs