apiVersion: apps/v1
kind: Deployment
metadata:
  name: sessionapi
spec:
  replicas: {{ .Values.sessionapi.replicas }}
  selector:
    matchLabels:
      app: sessionapi
  template:
    metadata:
      labels:
        app: sessionapi
    spec:
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
      containers:
        - name: sessionapi
          image: "{{ .Values.sessionapi.image.repository }}:{{ .Values.sessionapi.image.tag }}"
          ports:
            - containerPort: {{ .Values.sessionapi.containerPort }}
          volumeMounts:
            - mountPath: /app/wwwroot/StreamingAssets/network.json
              name: nginx-config
              subPath: network.json